const StaffData = [
  {
    id: 1,
    name: "Lois Kim",
    image: "https://i.imgur.com/jLjxZ3Y.jpg",
    nickname: "Empress of Everything",
    profession: "Financial Professional",
    YPTitle: "Co-Chair AKA Empress of ______",
    favMusic: "Everything but currently on a EDM phase.",
    favFood: "Anything Asian but I may be biased...",
    hobbies:
      "Volleyball, hanging with my dog, volunteering, and trying out new restaurants!",
    topVacationSpot: "Anything with a beach where I can just be a vegetable.",
  },
  {
    id: 2,
    name: "Landon Merigold",
    image: "https://i.imgur.com/H6Hpi4l.jpg",
    nickname: "",
    profession: "Loan Officer",
    YPTitle: "Minister of Culture / Co-chair",
    favMusic: "EDM and Country",
    favFood: "Chipotle or a Chicken Parm",
    hobbies: "Working Out, Golfing, Watching Sports",
    topVacationSpot:
      "Always up for a new adventure! My goal is to go to all 7 continents in my life! Good people to surround yourself with is all I ask for.",
  },
  {
    id: 3,
    name: "Nina Hernandez",
    image: "https://i.imgur.com/MtVek4f.jpg",
    nickname: "Tea-EO",
    profession: "Director of Communications & Events",
    YPTitle: "Tea-EO",
    favMusic: "Anything R&B",
    favFood: "WINGS!! Spicy & Crunchy, PLEASE!",
    hobbies:
      "I love going on long walks with my little family or finding anything to craft!",
    topVacationSpot: "Anywhere with a good view and great food!",
  },
  {
    id: 4,
    name: "Justus Carlile",
    image: "https://i.imgur.com/mCLG8BX.png",
    nickname: "Sheriff of Shindigs",
    profession: "Director of Communications & Events",
    YPTitle: "Sheriff of Shindigs",
    favMusic:
      "My tastes are wide but often wind up electronic, punk, country, or industrial/metal.",
    favFood: "Italian. Pasta is life.",
    hobbies:
      "Gardening, travel, home improvement projects, and lots and lots of concerts.",
    topVacationSpot:
      "Svalbard, Norway. Northernmost inhabited city in the world, and a place where polar bears outnumber people!",
  },
  {
    id: 5,
    name: "Josh Clark",
    image: "https://i.imgur.com/TEKSo83.jpg",
    nickname: "Sous Chef of Shindigs",
    profession: "Real Estate Agent",
    YPTitle: "Sous Chef of Shindigs",
    favMusic: "80's New Wave",
    favFood: "Anything smothered in Hot Honey",
    hobbies: "Rock climbing and running",
    topVacationSpot: "My house, I hate traveling",
  },
  {
    id: 6,
    name: "Kayla Baumann",
    image: "https://i.imgur.com/BsPLJX3.jpg",
    nickname: "Connection Connoisseur",
    profession:
      "Director of Community and Donor Engagement, Communities In Schools of North Texas",
    YPTitle: "Connection Connoisseur",
    favMusic: "Worship or Taylor Swift",
    favFood: "Pasta",
    hobbies:
      "Spending time with family & friends, puzzles, calligraphy, reading",
    topVacationSpot: "Great Smoky Mountains or Greece",
  },
  {
    id: 7,
    name: "Davis Perrone",
    image: "https://i.imgur.com/Qai4nql.png",
    nickname: "Digital Dynamo",
    profession: "Business Development Officer",
    YPTitle: "Digital Dynamo Social Media Co-Chair",
    favMusic: "Rap and Metal",
    favFood: "Buffalo Wings",
    hobbies: "Golf and Weightlifting",
    topVacationSpot: "I would love to go to Australia someday",
  },
  {
    id: 8,
    name: "David Sublett",
    image: "https://i.imgur.com/rCFOkqV.jpg",
    nickname: "N.E.R.D.",
    profession: "Financial Advisor",
    YPTitle: "N.E.R.D.",
    favMusic: "Indie Folk",
    favFood: "Mexican",
    hobbies: "Camping, anything pop culture-esque, pickling things",
    topVacationSpot: "Anywhere there are mountains",
  },
  {
    id: 9,
    name: "Kassandra Nordhoff",
    image: "https://i.imgur.com/mwBdzuw.jpg",
    nickname: "Social Media Sith Lord",
    profession: "Business Development Executive",
    YPTitle: "Social Media Sith Lord",
    favMusic: "Indie Folk",
    favFood: "Mexican",
    hobbies:
      "Trying out new restaurants, spending time with friends, and traveling",
    topVacationSpot: "Anywhere there are mountains",
  },
  {
    id: 10,
    name: "Edwin Choi",
    image: "https://i.imgur.com/7Lvsys0.jpg",
    nickname: "Software Sovereign",
    profession: "Web Developer & Software Engineer",
    YPTitle: "Software Sovereign",
    favMusic: "Alternative Rock, Electronic, and Epic Orchestra",
    favFood: "Steak, Salmon, and Snow Crab",
    hobbies: "Cooking, Reading, Web Design, and Voice Acting",
    topVacationSpot: "Singapore",
  },
];

export default StaffData;
